version: "3.5"

services:
  test-common-options:
    image: alpine:latest
    read_only: true
    command: /test.sh
    working_dir: /opt
    network_mode: host
    hostname: foohost
    domainname: capp.io
    volumes:
      - ./test-common-options.sh:/test.sh:ro
    environment:
      FOO: BAR
    # TODO tty: true - tty's not yet supported in capp-run

  test-user:
    image: alpine:latest
    command: /test.sh
    user: uucp:dialout
    network_mode: host
    volumes:
      - ./test-user.sh:/test.sh:ro
