version: "3.5"

services:
  test-common-options:
    image: alpine:latest
    read_only: true
    command: /test.sh
    working_dir: /opt
    network_mode: host
    hostname: foohost
    domainname: capp.io
    volumes:
      - ./test-common-options.sh:/test.sh:ro
    environment:
      FOO: BAR
    # TODO tty: true - tty's not yet supported in capp-run

  test-user:
    image: alpine:latest
    command: /test.sh
    user: uucp:dialout
    network_mode: host
    volumes:
      - ./test-user.sh:/test.sh:ro

  test-sysctls:
    image: alpine:latest
    command: /test.sh
    network_mode: host
    sysctls:
      net.core.somaxconn: 1234
    volumes:
      - ./test-sysctls.sh:/test.sh:ro

  test-oom_score_adj:
    image: alpine:latest
    command: /test.sh
    network_mode: host
    oom_score_adj: 1
    volumes:
      - ./test-oom.sh:/test.sh:ro

  test-capabilities:
    image: alpine:latest
    command: /test.sh
    network_mode: host
    privileged: true
    volumes:
      - ./test-caps.sh:/test.sh:ro
